# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sshmodemat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sshmodemat

  pod 'NMSSH'

  target 'sshmodemat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sshmodematTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
